### ISSUE TITLE
Images don't import

### ISSUE THREAD

**Issue by bpfilms** [mozilla/popcorn-editor#64]
Tried to import images - is there something I'm doing wrong?

**Comment by benrito** [comment]
Seems to be broken. @futuresoup has had some issues too

**Comment by futuresoup** [comment]
The images are importing, it's just that they are showing up on the timeline with completely smashed down resize handles so you can't see the image itself.

Look carefully on the timeline, you'll see a flat line, you can actually grab the top resize handle and stretch it up to reveal the image.

Trouble is - when you let go of the resize handle, it jumps back down to the bottom and makes the image unviewable again.

The solution involves changing the resize handles to default to a standard image size, and make sure that when they are moved around, they remain fixed in place.

**Comment by benrito** [comment]
sorry, @futuresoup 

@secretrobotron one other request: can we use an internet archive logo for the default image?

**Comment by secretrobotron** [comment]
Sure man! Can you file another issue for it?
